# -*- coding: utf-8 -*-
from . import machine_type
from . import enquiry_register
from . import workshop_config
from . import product_product
from . import contract
from . import initial_inspection
from . import parts_required
from . import other_charges
from . import mechanical_report
from . import worshop_quotation
from . import work_order
from . import sale_order
from . import material_request
from . import res_partner
from . import delivery_note
from . import delivery_note_line
from . import account_move
from . import product
from . import project_task
from . import workshop_scope_of_work
