# -*- coding: utf-8 -*-
{
    'name': 'Generator Service And Maintenance',
    'version': '13.0.7.3.2',
    'category': 'Maintenance',
    'summary': """This module includes the service and maintenance of the generator
    based on the annual maintenance contract and quotation raising for the services
    which have no running contracts""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['stock','sale', 'account_accountant', 'hr_timesheet', 'project_data', 'cy_timesheet_payroll',
                'sale_management', 'purchase', 'account_invoice_format','mail'],
    'data': [
        'security/generator_security.xml',
        'data/amc_expiration_cron.xml',
        'data/sequence.xml',
        'report/report.xml',
        'data/mail_form.xml',
        'views/res_partner_inherited_view.xml',
        'views/account_move_inherited.xml',
        'views/generator_type_view.xml',
        'views/technician_view.xml',
        'views/service_quotation_view.xml',
        'views/generator_service_view.xml',
        'views/material_request.xml',
        'views/annual_maintenance_contract_view.xml',
        'views/check_point_details_view.xml',
        'views/technician_timesheet_view.xml',
        'views/product_template.xml',
        'views/res_config_settings.xml',
        'report/service_report.xml',
        'report/service_monthly_report.xml',
        'report/material_request_report.xml',
        'report/service_status_report.xml',
        'report/service_completion_template.xml',
        'wizard/service_report.xml',
        'wizard/service_status.xml',
        'wizard/purchase_order_wizard_view.xml',
        'views/service_completion_view.xml',
        'security/ir.model.access.csv',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
