# -*- coding: utf-8 -*-
{
    'name': 'Electrical Services',
    'version': '13.0.1.1.0',
    'category': 'Maintenance',
    'summary': """This module includes work flow of electrical works.
    based on the annual maintenance contract""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['stock', 'account_accountant', 'purchase', 'project_data', 'hr_timesheet',
                'cy_timesheet_payroll', 'sale_management', 'account_invoice_format','mail'],
    'data': [
        'data/electrical_sequences.xml',
        'data/groups.xml',
        'data/electrical_journal.xml',
        'report/electrical_reports.xml',
        'data/email_template.xml',
        'security/ir.model.access.csv',
        'views/electrical_scope_view.xml',
        'views/product_product_inherited.xml',
        'views/product_template_inherited.xml',
        'views/amc_contract_view.xml',
        'views/enquiry_register_view.xml',
        'views/electrical_quotation_view.xml',
        'views/electrical_work_order_view.xml',
        'views/sale_order_inherited.xml',
        'views/project_task_inherited.xml',
        'views/material_request_view.xml',
        # 'views/res_config_settings.xml',
        'views/electrical_site_ref_view.xml',
        'report/monthly_report_template.xml',
        'wizard/report_wizard_view.xml',
        'report/electrical_report_quotation.xml',
        'report/material_request_pdf.xml',
        'views/completion_certificate.xml',
        'report/completion_certificate.xml',
        'wizard/certificate_view.xml',
        'wizard/purchase_order_wizard_view.xml',
        'report/report_certificate_template.xml'
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,

}
